# Site settings
title: Smart Home Cleaning
slogan: professional deep cleaning of residential and private properties
description: > # this means to ignore newlines until "baseurl:"
  Smart Home Cleaning professional deep cleaning of residential and private properties in Tenerife, Spain.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Smart Home Cleaning
email: 123dustfree@gmail.com
facebook_username: 123dustfree
twitter_username:
github_username:
address:
  - line: Tenerife South
  - line: Spain
  # Feel free to add more lines here 
telephone: +34 603 143 730
copyright:

# API settings
google_api_key: AIzaSyBsokSQtb9nCsMIgB4Cvt2UpmTq3DsIXLM
map:
  lng: -16.558277
  lat: 28.079174

# Build settings
markdown: kramdown